// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtoZxvej-gwZRjVYjOkIsxmhKagKUVQEY',
    appId: '1:742417345658:web:bf557faeb3c333d7981fc3',
    messagingSenderId: '742417345658',
    projectId: 'student-directory-85221',
    authDomain: 'student-directory-85221.firebaseapp.com',
    storageBucket: 'student-directory-85221.firebasestorage.app',
    measurementId: 'G-SWYNN6J3MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnoEGhpndsR6IRG7qtQH2R2HAPF4YKPVM',
    appId: '1:742417345658:android:93aeb2278537b208981fc3',
    messagingSenderId: '742417345658',
    projectId: 'student-directory-85221',
    storageBucket: 'student-directory-85221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ7MP3BNfKWW0u26V08_0uy_KZU95UA-E',
    appId: '1:742417345658:ios:5e6574bf986b613b981fc3',
    messagingSenderId: '742417345658',
    projectId: 'student-directory-85221',
    storageBucket: 'student-directory-85221.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ7MP3BNfKWW0u26V08_0uy_KZU95UA-E',
    appId: '1:742417345658:ios:5e6574bf986b613b981fc3',
    messagingSenderId: '742417345658',
    projectId: 'student-directory-85221',
    storageBucket: 'student-directory-85221.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtoZxvej-gwZRjVYjOkIsxmhKagKUVQEY',
    appId: '1:742417345658:web:422497675c50c60c981fc3',
    messagingSenderId: '742417345658',
    projectId: 'student-directory-85221',
    authDomain: 'student-directory-85221.firebaseapp.com',
    storageBucket: 'student-directory-85221.firebasestorage.app',
    measurementId: 'G-8N46278C6J',
  );
}
